[package]
name = "ferrocull-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono = { workspace = true }
dirs = { workspace = true }
fast_image_resize = { version = "6", features = ["rayon"] }
hex = "0.4"
image = { workspace = true }
kamadak-exif = { workspace = true }
quick-xml = "0.40"
rayon = "1.12"
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.11"
ferrocull-media = { workspace = true }
tempfile = { workspace = true }
thiserror.workspace = true
tracing.workspace = true
twox-hash = "2.1"

[lints]
workspace = true
